### ISSUE TITLE
[HELP] How to use it in local development

### ISSUE THREAD

**Issue by Gabriel-Gardin** [flamingo-run/django-cloud-tasks#25]
Hello, I was taking a look at this very nice project and would like to use it, however, I am not sure how I can mock the server behavior in local development. Any help would be appreciated. 

Thanks.

**Comment by joaodaher** [comment]
Hi @Gabriel-Gardin , in order to reproduce a realistic flow, such as `task-scheduled -> Cloud Tasks Queue -> Django view -> task-execution`, you would need to simulate the Cloud Tasks Queue part (basically a queue that makes POST requests).
This is not currently implemented.

When running locally, though, a task scheduled can be [executed synchronously if you set a settings's variable `EAGER_TASKS=True`](https://github.com/flamingo-run/django-cloud-tasks/blob/main/django_cloud_tasks/tasks/task.py#L102). It's not **exactly** what would happen inside GCP, but it's close because the task is being executed.

**Comment by Gabriel-Gardin** [comment]
Oh, I get it. That's great. Thanks
